font: 'NotoSerif-SemiCondensedMedium.ttf'
fontSize: '256'
#padding-top: 100
#padding-bottom: 100
#padding-left: 100
#padding-right: 100
padding: 100
logo: 'ZJ'
output: './zj.svg'
path:
  fill: '#2b68a7'
